name: Child Workflow

on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string

jobs:
    example_job:
        runs-on: ubuntu-latest
        steps:
        - name: Print Input
          run: |
            echo "The input value is: ${{ inputs.example_input }}"

