name: Child Workflow

on:
  workflow_call:
    inputs:
      example_input:
        required: true
        type: string

permissions:
  actions: write
  contents: write
  pull-requests: write
  repository-projects: write
  
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - name: Print Input
      run: |
        echo "The input value is: ${{ inputs.example_input }}"

    - name: env
      run: |
        printenv | sort

    - name: github JSON
      run: |
        echo '${{ toJson(github) }}'

    - name: job JSON
      run: |
        echo '${{ toJson(job) }}'
    
    - name: checkout
      uses: actions/checkout@v3

    - name: call helper workflow
      ## Note that the helper_run_id is used for telemetry correlation
      ## If you make changes to this format, you will need to update the telemetry code
      run: |
        helper_run_id="helper-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-${{github.job}}"
        gh workflow run helper.yml \
          --repo "${{ github.repository }}" \
          --ref "${{ github.head_ref }}" \
          -f helper_input="Value from Child" \
          -f helper_run_id="$helper_run_id"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


