name: Helper Workflow
run-name: 'helper: ${{ inputs.helper_run_id }}'
on:
  workflow_dispatch:
    inputs:
      helper_input:
        required: true
        type: string
      helper_run_id:
        required: true
        type: string

jobs:
  do_work:
    runs-on: ubuntu-latest
    steps:
    - name: Print Input
      run: |
        echo "The input value is: ${{ inputs.helper_input }}"
    - name: Print Run ID
      run: |
        echo "The Run ID is: ${{ inputs.helper_run_id }}"
    - name: Pretend to work
      run: |
        echo "Doing some work here..."
        sleep 10
        echo "Work completed."
