name: Published Artifact Test

on:
  workflow_dispatch:
 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for all branches and tags (may not be needed if using PR API for changed files)

      - name: Prep Local Actions
        uses: ./.github/actions/prep_local_actions

      - name: Show event info
        run: |
          echo '${{ toJson(github)}}'

      - name: Get ref for cache
        id: get_ref
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            console.log(JSON.stringify(context, null, 2))

            // TODO - tidy this up, make more robust (e.g. parsing ref)

            const eventName = context.eventName;
            switch(eventName) {
              case 'pull_request':
                console.log("PR event");
                console.log(`Using ref: ${context.payload.pull_request.base.ref}`);
                return context.payload.pull_request.base.ref
              
              case "push":
                return context.payload.ref.split("/")[2];

              case "merge_group":
                return context.payload.merge_group.base_ref.split("/")[2];
                break;

              case "workflow_dispatch":
                return context.payload.ref.split("/")[2];

              default:
                core.setFailed(`Unhandled event type: ${eventName}`)
                break;
            }

      - name: Azure login with federated credentials
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Check for artifacts
        id: check_artifacts
        uses: testing-turtle/transient-terrapin@check_artifacts-v1
        with:
          filter-file: ./scripts/example-filter.yaml
          storage-account: ${{ vars.AZURE_STORAGE_ACCOUNT }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          container: artifacts # ensure this exists
          base-ref: origin/${{ steps.get_ref.outputs.result }}

