name: ssh-test

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: [self-hosted, ManagedDevOps.Pool=tt-pool2]
    # runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Start sshd
        env:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          sudo ./setup-sshd.sh

      - name: IP Address
        run: curl https://ifconfig.me

      - name: Wait...
        run: sleep 300
